### ISSUE TITLE
Conversion error with progressive cut and only 1 pass

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#1009]
Wenn man Durchgänge auf 1 Stellt und den Haken bei "Progressive Cut" setzt - failed die Konvertierung (da teilt wahrscheinlich was durch 0) - ist natürlich eine Sinnfreie Einstellung aber sollte dennoch nicht failen

Google translate:
If you set passes to 1 and check the box next to "Progressive Cut" - the conversion failed (because it probably divides something by 0) - is of course a pointless setting, but it should not fail

**Comment by Gallore** [comment]
```
20-09-23 08:34:37,397 - octoprint.plugins.mrbeam - ERROR - Conversion error (Second argument to a division or modulo operation was zero.): float division by zero
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/__init__.py", line 2450, in do_slice
    is_job_cancelled, on_progress, on_progress_args, on_progress_kwargs
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/gcodegenerator/converter.py", line 531, in convert
    f = round(fr * (1 - 0.5 * p / (passes - 1)))
ZeroDivisionError: float division by zero
```
