### ISSUE TITLE
Image: SW Update - Git Error: "Please tell me who you are"

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#106]
Git error while updating OctoPrint: 
```fatal: empty ident name (for <pi@MrBeam2-79D7.(none)>) not allowed```

Here is what we can do: https://stackoverflow.com/questions/11656761/git-please-tell-me-who-you-are-error

```
Updating, please wait.
++++++++++++++++++++++++++++++++++
Now updating OctoPrint to v1.3.4.1
++++++++++++++++++++++++++++++++++
/home/pi/oprint/bin/python "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/softwareupdate/scripts/update-octoprint.py" --branch= --force=true "/home/pi/OctoPrint" v1.3.4.1
From https://github.com/mrbeam/OctoPrint
fa5260a..4c6dfed  mrbeam2-stable -> origin/mrbeam2-stable
* [new tag]         v1.3.4.1   -> v1.3.4.1
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for <pi@MrBeam2-79D7.(none)>) not allowed
Traceback (most recent call last):
File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/softwareupdate/scripts/update-octoprint.py", line 313, in <module>
main()
File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/softwareupdate/scripts/update-octoprint.py", line 309, in main
update_source(git_executable, folder, args.target, force=args.force, branch=args.branch)
File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.3.4-py2.7.egg/octoprint/plugins/softwareupdate/scripts/update-octoprint.py", line 229, in update_source
raise RuntimeError("Could not update, \"git pull\" failed with returncode {}".format(returncode))
RuntimeError: Could not update, "git pull" failed with returncode 128
Python executable: '/home/pi/oprint/bin/python'
>>> Running: git diff --shortstat
> git diff --shortstat
>>> Running: git fetch
> git fetch
>>> Running: git pull
> git pull
The update did not finish successfully. Please consult the log for details.
```

**Comment by make-ing** [comment]
Done, testing needed:

https://bitbucket.org/mrbeam/octopi/commits/d4a5ae4cca62f3c311221e7ff298b54275fb396a
