### ISSUE TITLE
svg conversion crashes with this file

### ISSUE THREAD

**Issue by hungerpirat** [mrbeam/MrBeamPlugin#113]
Error log says: 
```
2017-07-06 08:06:49,815 - octoprint.plugins.mrbeam - ERROR - Conversion error (Second argument to a division or modulo operation was zero.): float division by zero
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/__init__.py", line 1018, in do_slice
    engine.convert(on_progress, on_progress_args, on_progress_kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/gcodegenerator/converter.py", line 223, in convert
    curvesD[colorKey] = self._parse_curve(pD[colorKey], layer)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/gcodegenerator/converter.py", line 479, in _parse_curve
    c += biarc(sp1,sp2,0,0) if w==None else biarc(sp1,sp2,-f(w[k][i-1]),-f(w[k][i]))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/gcodegenerator/biarc.py", line 36, in biarc
    r = TS.mag()/v.mag()*2
ZeroDivisionError: float division by zero
```

[Triangled_earth_for_laser.svg.zip](https://github.com/mrbeam/MrBeamPlugin/files/1127225/Triangled_earth_for_laser.svg.zip)

**Comment by Gallore** [comment]
Still reproducible with gc_nextgen.

However, I got this Exception:
```
2017-10-04 13:19:20,249 - octoprint.plugins.mrbeam - ERROR - Conversion error (Inappropriate argument type.): 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/__init__.py", line 1212, in do_slice
    engine.convert(on_progress, on_progress_args, on_progress_kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/gcodegenerator/converter.py", line 206, in convert
    self._log.info("path %s, %s, stroke: %s, fill: %s, mb:gc: %s" % ( layer.get('id'), path.get('id'), path.get('stroke'), path.get('class'), path.get(_add_ns('gc', 'mb'))[:100] ))
TypeError: 'NoneType' object has no attribute '__getitem__'
```

On Chrome Console we get these errors:
```
15:17:41.067 snap.svg-min.js:19 Error: <path> attribute d: Expected number, "MZ".
d @ snap.svg-min.js:19
15:17:41.068 snap.svg-min.js:19 Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "Z".
d @ snap.svg-min.js:19
15:17:42.232 path_magic.js:507 Uncaught TypeError: Cannot read property 'push' of undefined
    at Object.module.parse (path_magic.js:507)
    at snap_gc_plugin.js:62
    at i.j.forEach (snap.svg-min.js:21)
    at s.Element.embed_gc (snap_gc_plugin.js:30)
    at WorkingAreaViewModel.self._prepareAndInsertSVG (working_area.js:494)
    at cb (working_area.js:428)
    at snap.svg-min.js:19
    at c (snap.svg-min.js:19)
    at eve (snap.svg-min.js:19)
    at XMLHttpRequest.g.onreadystatechange (snap.svg-min.js:19)
15:18:00.441 path_magic.js:507 Uncaught TypeError: Cannot read property 'push' of undefined
    at Object.module.parse (path_magic.js:507)
    at snap_gc_plugin.js:62
    at i.j.forEach (snap.svg-min.js:21)
    at s.Element.embed_gc (snap_gc_plugin.js:30)
    at working_area.js:490
    at s.Element.ftAfterTransform (drag_scale_rotate.js:347)
    at s.Element.ftRemoveHandles (drag_scale_rotate.js:249)
    at WorkingAreaViewModel.self.abortFreeTransforms (working_area.js:1365)
    at MotherViewModel.VectorConversionViewModel.self.show_conversion_dialog (convert.js:247)
    at HTMLButtonElement.<anonymous> (knockout.js:89)
15:18:55.080 snap.svg-min.js:19 Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "Z".
k.clone @ snap.svg-min.js:19
WorkingAreaViewModel.self.getCompositionSVG @ working_area.js:1379
VectorConversionViewModel.self.convert @ convert.js:409
(anonymous) @ VM1845:3
(anonymous) @ knockout.js:89
dispatch @ jquery.js:4737
elemData.handle @ jquery.js:4549
15:18:55.153 snap.svg-min.js:19 Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "Z".
k.clone @ snap.svg-min.js:19
WorkingAreaViewModel.self.renderInfill @ working_area.js:1652
WorkingAreaViewModel.self.getCompositionSVG @ working_area.js:1394
VectorConversionViewModel.self.convert @ convert.js:409
(anonymous) @ VM1845:3
(anonymous) @ knockout.js:89
dispatch @ jquery.js:4737
elemData.handle @ jquery.js:4549
15:18:56.138 snap.svg-min.js:20 Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "Z".
h.toString @ snap.svg-min.js:20
(anonymous) @ snap.svg-min.js:19
WorkingAreaViewModel.self._wrapInSvgAndScale @ working_area.js:1401
(anonymous) @ working_area.js:1395
cb @ working_area.js:1691
source.onload @ render_fills.js:143
```
