### ISSUE TITLE
Software Update not working

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#1212]
<img width="1257" alt="Screenshot 2021-03-19 at 17 39 07" src="https://user-images.githubusercontent.com/4582388/111823066-cb51f880-88e4-11eb-875c-05de5fa802df.png">

```
2021-03-19 17:52:25,663 - octoprint.plugins.softwareupdate - ERROR - Error while retrieving update information from plugin mrbeam
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 111, in _get_configured_checks
    hook_checks = hook()
  File "/home/pi/sources/OctoPrint-MrBeam/octoprint_mrbeam/__init__.py", line 2530, in get_update_information
    return get_update_information(self)
  File "/home/pi/sources/OctoPrint-MrBeam/octoprint_mrbeam/software_update_information.py", line 51, in get_update_information
    _set_info_rpiws281x(self, tier)
NameError: global name '_set_info_rpiws281x' is not defined
```

**Comment by amrsoll** [comment]
From the f_packaging_beamos branch.

Fixed in e70bd7a
