### ISSUE TITLE
Repeated auto user Logout when using the WiFi (and eth?)

### ISSUE THREAD

**Issue by amrsoll** [mrbeam/MrBeamPlugin#1227]
When connecting to a wifi (in this case "Mr Beam"), it would automatically disconnect the user. It does it repeatedly, as if it fails to login at all.

EDIT : It would seem that there might be a DNS resolution issue

This does Not seem to happen when I remove the ethernet cable from the device. Perhaps there could be some confused ip address : device mapping.

### Some access restriction

normal when the user is not auth'ed, but perhaps it's not able to use the auth api ? 
```
tornado.access WARNING 401 GET /api/users (127.0.0.1) 11.47ms
```

### A lot of recursion depth "exceedation"
```
10:26:45 octoprint.server.util.sockjs WARNING Could not send message to client ::ffff:10.42.0.1: maximum recursion depth exceeded while calling a Python object
```
And even a stack trace

```
tornado.application ERROR Uncaught exception POST /sockjs/031/p2jusfxr/xhr_streaming?t=1617873977971 (127.0.0.1)
 HTTPServerRequest(protocol='http', host='mrbeam-c12b.local', method='POST', uri='/sockjs/031/p2jusfxr/xhr_streaming?t=1617873977971', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://mrbeam-c12b.local', 'Content-Length': '0', 'Sec-Gpc': '1', 'Accept-Language': 'en', 'Accept-Encoding': 'gzip, deflate', 'X-Forwarded-For': '::ffff:10.42.0.1', 'X-Scheme': 'http', 'Host': 'mrbeam-c12b.local', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36', 'Connection': 'close', 'Referer': 'http://mrbeam-c12b.local/', 'Cookie': 'JSESSIONID=dummy; session_P80=.eJyrVorPTFGyqlZSSFKyUvKtcsryDQ_K8M31rfB3jyyPcvc1jjTyNPbLisr1DcnJ9c1KN_R398qIDHG1VarVUcpMSc0rySyp1EssLcmIL6ksSFWyyivNyUGSAZkOEqoFADFrJBY.YG7MOQ.swZRQiIvctVQ33Mvv3U4QCndaiI'})
 Traceback (most recent call last):
   File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/web.py", line 1332, in _execute
     result = method(*self.path_args, **self.path_kwargs)
   File "/home/pi/oprint/local/lib/python2.7/site-packages/sockjs/tornado/util.py", line 102, in wrapper
     result = method(self, *args, **kwargs)
   File "/home/pi/oprint/local/lib/python2.7/site-packages/sockjs/tornado/transports/xhrstreaming.py", line 34, in post
>    self.session.flush()
>  File "/home/pi/oprint/local/lib/python2.7/site-packages/sockjs/tornado/session.py", line 363, in flush
>    self.handler.send_pack('a[%s]' % self.send_queue)
>  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/util/sockjs.py", line 36, in send_pack
>    return orig_send_pack(*args, **kwargs)
>  File "/home/pi/oprint/local/lib/python2.7/site-packages/sockjs/tornado/transports/xhrstreaming.py", line 46, in send_pack
>    self.flush().add_done_callback(self.send_complete)
>  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/concurrent.py", line 134, in add_done_callback
>    fn(self)
>  File "/home/pi/oprint/local/lib/python2.7/site-packages/sockjs/tornado/transports/streamingbase.py", line 47, in send_complete
^ repeated x 158
     self.session.flush()
   File "/home/pi/oprint/local/lib/python2.7/site-packages/sockjs/tornado/session.py", line 363, in flush
     self.handler.send_pack('a[%s]' % self.send_queue)
   File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/util/sockjs.py", line 36, in send_pack
     return orig_send_pack(*args, **kwargs)
   File "/home/pi/oprint/local/lib/python2.7/site-packages/sockjs/tornado/transports/xhrstreaming.py", line 46, in send_pack
     self.flush().add_done_callback(self.send_complete)
   File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/web.py", line 855, in flush
     return self.request.connection.write(chunk, callback=callback)
   File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/http1connection.py", line 417, in write
     future = self._write_future = Future()
 RuntimeError: maximum recursion depth exceeded while calling a Python object
```

### The wifi status check might be triggered "too soon"

When there is a long connection delay, it could be that there is a connection check while trying to connect. If the check sees that it's not connected to a WiFi, it will start the AP mode, thus creating more confusion for the browser.

`netconnectd.log` (psk hidden)
```
2021-04-08 11:09:19,132 - netconnectd.server - INFO - Waiting for connection on socket...
2021-04-08 11:09:42,019 - netconnectd.server - INFO - Recv: b'{"config_wifi":{'
2021-04-08 11:09:42,020 - netconnectd.server - INFO - Recv: b'"psk":"********'
2021-04-08 11:09:42,020 - netconnectd.server - INFO - Recv: b'********","force":'
2021-04-08 11:09:42,021 - netconnectd.server - INFO - Recv: b'false,"ssid":"Mr'
2021-04-08 11:09:42,021 - netconnectd.server - INFO - Recv: b' Beam"}}\x00'
2021-04-08 11:09:42,648 - netconnectd.server - INFO - Saved configuration for wifi Mr Beam
2021-04-08 11:09:42,648 - netconnectd.server - INFO - Send: {"result":"configured wifi as \"netconnectd_wifi\""}
2021-04-08 11:09:42,649 - netconnectd.server - INFO - Waiting for connection on socket...
2021-04-08 11:09:42,651 - netconnectd.server - INFO - Recv: b'{"start_wifi":{}'
2021-04-08 11:09:42,652 - netconnectd.server - INFO - Recv: b'}\x00'
2021-04-08 11:09:42,670 - netconnectd.server - INFO - Access Point is currently running, will restore if wifi starting fails!
2021-04-08 11:09:53,628 - netconnectd.server - INFO - Connected to wifi ['Mr Beam']
2021-04-08 11:09:53,629 - netconnectd.server - INFO - Send: {"result":"connected to wifi"}
2021-04-08 11:09:53,632 - netconnectd.server - INFO - Waiting for connection on socket...
2021-04-08 11:09:53,715 - netconnectd.server - INFO - Only wired link active, starting access point
2021-04-08 11:09:53,716 - netconnectd.server - INFO - Starting up access point
2021-04-08 11:09:54,930 - wifi.ap - INFO - Started hostapd: ...
```

**Comment by Gallore** [comment]
This is a know behaviour also of the old image and old netconnectd:
When I switch the connection type of my laptop (from Wifi to cable by plugging in the cable) I get logged out and need to re-login.
