### ISSUE TITLE
Software update error - new Image build 2021-04-27

### ISSUE THREAD

**Issue by Josef-MrBeam** [mrbeam/MrBeamPlugin#1246]
I get an error if I try to update the mrbeam plugin via the UI
 ```
2021-04-27 15:04:39,070 - octoprint.plugins.mrbeam.led_events - INFO - Executing a system command
2021-04-27 15:04:39,165 - octoprint.plugins.mrbeam - INFO - on_event ClientOpened: {'remoteAddress': '2003:ea:b747:a500:425:dce4:faed:8b7d'}
2021-04-27 15:04:39,171 - octoprint.plugins.mrbeam - INFO - fire_event() event:MrbPluginVersion, payload:{'version': '0.9.1.2', 'is_first_run': False, 'mrb_state': {'fan_connected': True, 'lid_fully_open': False, 'dusting_mode': False, 'fan_rpm': 0.0, 'interlocks_closed': True, 'pause_mode': False, 'rtl_mode': False, 'is_homed': False, 'cooling_mode': False, 'fan_state': 0.0, 'state': 'Locked', 'compressor_state': 0, 'interlocks_open': [], 'laser_temp': 32.7, 'fan_dust': 0.377}}
2021-04-27 15:04:39,176 - octoprint.plugins.mrbeam - INFO - on_event MrbPluginVersion: {'version': '0.9.1.2', 'is_first_run': False, 'mrb_state': {'fan_connected': True, 'lid_fully_open': False, 'dusting_mode': False, 'fan_rpm': 0.0, 'interlocks_closed': True, 'pause_mode': False, 'rtl_mode': False, 'is_homed': False, 'cooling_mode': False, 'fan_state': 0.0, 'state': 'Locked', 'compressor_state': 0, 'interlocks_open': [], 'laser_temp': 32.7, 'fan_dust': 0.377}}
2021-04-27 15:04:51,547 - octoprint.plugins.softwareupdate - WARNING - Cannot perform update for octoprint, update type is not fully configured
2021-04-27 15:04:51,559 - octoprint.plugins.softwareupdate - INFO - Starting update of mrbeam to aa12ebb29c585f73a060bc6bcbebaec0565651ec...
2021-04-27 15:04:52,618 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2021-04-27 15:04:53,679 - octoprint.util.pip - INFO - Version of pip is 20.3.4
2021-04-27 15:04:57,252 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages/, --user flag needed => no, virtual env => yes
2021-04-27 15:04:57,262 - octoprint.plugins.softwareupdate - ERROR - Update of mrbeam can not be performed
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 908, in _perform_update
    update_result = updater.perform_update(target, populated_check, target_version, log_cb=self._log, online=online)
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/updaters/pip.py", line 79, in perform_update
    returncode, stdout, stderr = pip_caller.execute(*pip_args)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/pip.py", line 171, in execute
    return self.call(command, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/commandline.py", line 83, in call
    p = sarge.run(command, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/sarge/__init__.py", line 1462, in run
    p.run(input=input, async_=async_)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/sarge/__init__.py", line 1071, in run
    self.run_node(node, input=input, async_=False)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/sarge/__init__.py", line 1187, in run_node
    result = getattr(self, method)(node, input, async_)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/sarge/__init__.py", line 1333, in run_command_node
    node.cmd.run(input=input, async_=async_)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/sarge/__init__.py", line 655, in run
    self.process = p = Popen(self.args, **self.kwargs)
TypeError: __init__() got an unexpected keyword argument 'async'

```

**Comment by Josef-MrBeam** [comment]
pip install sarge==0.1.4 helps to fix this error
