### ISSUE TITLE
Update blocker: ssh key in root has too wide permission 

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#272]
Update blocker: ssh key in root has too wide permission

Error message while updating iobeam:
```
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Now updating iobeam to c078cad777b24554a445f5dade25ad3a21ca28b9
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
sudo /usr/local/bin/pip install git+ssh://git@bitbucket.org/mrbeam/iobeam.git@c078cad777b24554a445f5dade25ad3a21ca28b9
Collecting git+ssh://git@bitbucket.org/mrbeam/iobeam.git@c078cad777b24554a445f5dade25ad3a21ca28b9
Cloning ssh://git@bitbucket.org/mrbeam/iobeam.git (to c078cad777b24554a445f5dade25ad3a21ca28b9) to /tmp/pip-YXPLIb-build
Warning: Permanently added the RSA host key for IP address '104.192.143.1' to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/root/.ssh/id_rsa' are too open.
It is recommended that your private key files are NOT accessible by others.
This private key will be ignored.
key_load_private_type: bad permissions
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Command "git clone -q ssh://git@bitbucket.org/mrbeam/iobeam.git /tmp/pip-YXPLIb-build" failed with error code 128 in None
You are using pip version 9.0.1, however version 9.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by Gallore** [comment]
Octoprint log:
```
2018-03-20 10:54:35,880 - octoprint.plugins.softwareupdate - ERROR - Update of iobeam can not be performed
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-v1.3.6-py2.7.egg/octoprint/plugins/softwareupdate/__init__.py", line 908, in _perform_update
    update_result = updater.perform_update(target, populated_check, target_version, log_cb=self._log, online=online)
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-v1.3.6-py2.7.egg/octoprint/plugins/softwareupdate/updaters/pip.py", line 81, in perform_update
    raise exceptions.UpdateError("Error while executing pip install", (stdout, stderr))
UpdateError
```
