### ISSUE TITLE
Exception in iobeam: list index out of range

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#85]
on device mrbeam2-E71F.local
[iobeam (1).log.zip](https://github.com/mrbeam/MrBeamPlugin/files/1040721/iobeam.1.log.zip)

'''
2017-05-31 07:08:51,615 - iobeam.iobeam - INFO - ###### i
obeam starting ###### loglevel: DEBUG
2017-05-31 07:08:51,822 - iobeam.iobeam - INFO - waiting for connection...
2017-05-31 07:08:52,294 - iobeam.iobeam - INFO - client connected!
2017-05-31 07:08:52,296 - iobeam.iobeam - DEBUG - ### Starting up I2C thread...
2017-05-31 07:13:13,495 - iobeam.iobeam - DEBUG - Send: 'steprun:en\n'
2017-05-31 07:13:24,181 - iobeam.iobeam - DEBUG - Send: 'steprun:di\n'
2017-05-31 07:14:09,165 - iobeam.iobeam - DEBUG - Send: 'intlk:op:1\n'
2017-05-31 07:14:09,257 - iobeam.iobeam - DEBUG - Send: 'intlk:op:0\n'
2017-05-31 07:14:10,244 - iobeam.iobeam - DEBUG - Send: 'lid:pr\n'
2017-05-31 07:14:20,554 - iobeam.iobeam - DEBUG - Send: 'lid:rl\n'
2017-05-31 07:14:21,208 - iobeam.iobeam - DEBUG - Send: 'intlk:cl:0\n'
2017-05-31 07:14:21,422 - iobeam.iobeam - DEBUG - Send: 'intlk:cl:1\n'
2017-05-31 07:14:57,939 - iobeam.iobeam - DEBUG - Send: 'onebtn:pr\n'
2017-05-31 07:14:58,143 - iobeam.iobeam - DEBUG - Send: 'onebtn:dn:0.2\n'
2017-05-31 07:14:58,357 - iobeam.iobeam - DEBUG - Send: 'onebtn:rl:0.4\n'
2017-05-31 07:14:58,491 - iobeam.iobeam - DEBUG - Send: 'steprun:en\n'
2017-05-31 07:18:32,142 - iobeam.iobeam - DEBUG - Send: 'steprun:di\n'
2017-05-31 07:18:45,136 - iobeam.iobeam - DEBUG - Send: 'onebtn:pr\n'
2017-05-31 07:18:45,340 - iobeam.iobeam - DEBUG - Send: 'onebtn:dn:0.2\n'
2017-05-31 07:18:45,545 - iobeam.iobeam - DEBUG - Send: 'onebtn:dn:0.4\n'
2017-05-31 07:18:45,759 - iobeam.iobeam - DEBUG - Send: 'onebtn:rl:0.6\n'
2017-05-31 07:22:40,406 - iobeam.iobeam - DEBUG - Send: 'steprun:en\n'
2017-05-31 07:22:45,761 - iobeam.iobeam - DEBUG - Send: 'steprun:di\n'
2017-05-31 07:28:08,622 - iobeam.iobeam - DEBUG - Send: 'onebtn:pr\n'
2017-05-31 07:28:08,835 - iobeam.iobeam - DEBUG - Send: 'onebtn:rl:0.2\n'
2017-05-31 07:28:08,958 - iobeam.iobeam - DEBUG - Send: 'steprun:en\n'
2017-05-31 07:29:07,050 - iobeam.iobeam - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/iobeam/i2c_thread.py", line 101, in int_handler
    self.generate_queue_msg(i, now, 0)
  File "/usr/local/lib/python2.7/dist-packages/iobeam/i2c_thread.py", line 107, in generate_queue_msg
    p = self.input_list[bit]
IndexError: list index out of range
2017-05-31 07:34:38,680 - iobeam.iobeam - DEBUG - Send: 'intlk:op:0\n'
2017-05-31 07:34:38,691 - iobeam.iobeam - DEBUG - Send: 'intlk:op:1\n'
2017-05-31 07:34:38,702 - iobeam.iobeam - DEBUG - Send: 'intlk:op:2\n'
2017-05-31 07:34:38,713 - iobeam.iobeam - DEBUG - Send: 'intlk:op:3\n'
2017-05-31 07:34:38,723 - iobeam.iobeam - DEBUG - Send: 'lid:pr\n'
2017-05-31 07:35:03,917 - iobeam.iobeam - DEBUG - Send: 'onebtn:pr\n'
2017-05-31 07:38:15,922 - iobeam.iobeam - INFO - ###### iobeam starting ###### loglevel: DEBUG
2017-05-31 07:38:16,126 - iobeam.iobeam - INFO - waiting for connection...
'''

**Comment by Gallore** [comment]
https://bitbucket.org/mrbeam/iobeam/commits/73e78f5beaf18174878ecdb23d8c3fccf20a943c
