### ISSUE TITLE
Exception in iobeam: Broken pipe

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#86]
[iobeam (1).log.zip](https://github.com/mrbeam/MrBeamPlugin/files/1040723/iobeam.1.log.zip)

'''
2017-05-19 08:58:21,324 - iobeam.iobeam - DEBUG - ### Starting up I2C thread...
2017-05-19 08:58:47,057 - iobeam.iobeam - DEBUG - Send: 'steprun:en\n'
2017-05-19 08:58:51,896 - iobeam.iobeam - DEBUG - Send: 'steprun:di\n'
2017-05-19 09:00:20,835 - iobeam.iobeam - DEBUG - Send: 'steprun:en\n'
2017-05-19 09:00:31,761 - iobeam.iobeam - DEBUG - Send: 'steprun:di\n'
2017-05-19 09:02:06,245 - iobeam.iobeam - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/usr/local/bin/iobeam", line 9, in <module>
    load_entry_point('iobeam==0.2.3', 'console_scripts', 'iobeam')()
  File "/usr/local/lib/python2.7/dist-packages/iobeam/iobeam.py", line 180, in main
    s.start()
  File "/usr/local/lib/python2.7/dist-packages/iobeam/iobeam.py", line 82, in start
    con.sendall(".\n")
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe
2017-05-19 09:33:39,944 - iobeam.iobeam - INFO - ###### iobeam starting ###### loglevel: DEBUG
'''

**Comment by Gallore** [comment]
Duplicate & Already Fixed
