### ISSUE TITLE
Camera Calibration : Lasering markers when device locked

### ISSUE THREAD

**Issue by amrsoll** [mrbeam/MrBeamPlugin#867]
If you try to laser the markers while the device is not homed, it will let you choose the material and even finish slicing, but won't laser.
It does not display any error in the front end.
```
octoprint.plugins.mrbeam.iobeam.onebutton_handler ERROR Error while going into state ReadyToLaser: ReadyToLaser: printer is not ready. printer state is: LOCKED
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/iobeam/onebutton_handler.py", line 243, in onEvent
    self.set_ready_to_laser(filename)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/iobeam/onebutton_handler.py", line 299, in set_ready_to_laser
    self._test_conditions(gcode_file)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mrbeam/iobeam/onebutton_handler.py", line 377, in _test_conditions
    raise Exception("ReadyToLaser: printer is not ready. printer state is: %s" % self._printer.get_state_id())
Exception: ReadyToLaser: printer is not ready. printer state is: LOCKED
```

See also #250

**Comment by amrsoll** [comment]
https://trello.com/c/fmcIAzcP/609-fix-camera-calibration-lasering-markers-when-device-locked
